version: 2

sources:
  - name: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: product
        identifier: raw_gz_product
        description: product
        columns:
         - name: products_id
           description: Primary key of the table
           tests:
             - unique
             - not_null
                 
      - name: sales
        identifier: raw_gz_sales
        freshness: 
          error_after:
            count: 90
            period: day
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"

        description: sales of greenweez / we have one row per product_id found in each orders_id
        columns:
         - name: date_date
           description: Date of the order
         - name: orders_id
           description: Foreign key corresponding to the order number
         - name: pdt_id
           description: Foreign key corresponding to the product ID
         - name: revenue
           description: total turnover generated by the sales of this product in this order
         - name: quantity
           description: number of similar products included in this order
        ##tests:
         ##- unique:
            ##column_name: "(orders_id || '-' || pdt_id)"
             ## OR ##
          ##- dbt_utils.unique_combination_of_columns:
             ##combination_of_columns:
             ## - orders_id
              ##- pdt_id

      - name: ship
        identifier: raw_gz_ship
        description: ship
        columns:
         - name: orders_id
           description: Primary key of the table
           tests:
             - unique
             - not_null
